/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.grpc_web_hacker_news.GetStoryRequest', null, global);
goog.exportSymbol('proto.grpc_web_hacker_news.GetStoryResponse', null, global);
goog.exportSymbol('proto.grpc_web_hacker_news.Item', null, global);
goog.exportSymbol('proto.grpc_web_hacker_news.ItemId', null, global);
goog.exportSymbol('proto.grpc_web_hacker_news.ItemType', null, global);
goog.exportSymbol('proto.grpc_web_hacker_news.ListStoriesRequest', null, global);
goog.exportSymbol('proto.grpc_web_hacker_news.ListStoriesResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_web_hacker_news.ItemId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_web_hacker_news.ItemId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_web_hacker_news.ItemId.displayName = 'proto.grpc_web_hacker_news.ItemId';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ItemId.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_web_hacker_news.ItemId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_web_hacker_news.ItemId} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ItemId.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_web_hacker_news.ItemId}
 */
proto.grpc_web_hacker_news.ItemId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_web_hacker_news.ItemId;
  return proto.grpc_web_hacker_news.ItemId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_web_hacker_news.ItemId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_web_hacker_news.ItemId}
 */
proto.grpc_web_hacker_news.ItemId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.ItemId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_web_hacker_news.ItemId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_web_hacker_news.ItemId} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_web_hacker_news.ItemId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.grpc_web_hacker_news.ItemId.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.grpc_web_hacker_news.ItemId.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_web_hacker_news.Item = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_web_hacker_news.Item, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_web_hacker_news.Item.displayName = 'proto.grpc_web_hacker_news.Item';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_web_hacker_news.Item.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_web_hacker_news.Item.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_web_hacker_news.Item} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_web_hacker_news.Item.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto.grpc_web_hacker_news.ItemId.toObject(includeInstance, f),
    score: jspb.Message.getFieldWithDefault(msg, 2, 0),
    title: jspb.Message.getFieldWithDefault(msg, 3, ""),
    by: jspb.Message.getFieldWithDefault(msg, 4, ""),
    time: jspb.Message.getFieldWithDefault(msg, 5, 0),
    url: jspb.Message.getFieldWithDefault(msg, 6, ""),
    type: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_web_hacker_news.Item}
 */
proto.grpc_web_hacker_news.Item.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_web_hacker_news.Item;
  return proto.grpc_web_hacker_news.Item.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_web_hacker_news.Item} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_web_hacker_news.Item}
 */
proto.grpc_web_hacker_news.Item.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.grpc_web_hacker_news.ItemId;
      reader.readMessage(value,proto.grpc_web_hacker_news.ItemId.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScore(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBy(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTime(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 7:
      var value = /** @type {!proto.grpc_web_hacker_news.ItemType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.Item.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_web_hacker_news.Item.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_web_hacker_news.Item} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_web_hacker_news.Item.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.grpc_web_hacker_news.ItemId.serializeBinaryToWriter
    );
  }
  f = message.getScore();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBy();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTime();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional ItemId id = 1;
 * @return {?proto.grpc_web_hacker_news.ItemId}
 */
proto.grpc_web_hacker_news.Item.prototype.getId = function() {
  return /** @type{?proto.grpc_web_hacker_news.ItemId} */ (
    jspb.Message.getWrapperField(this, proto.grpc_web_hacker_news.ItemId, 1));
};


/** @param {?proto.grpc_web_hacker_news.ItemId|undefined} value */
proto.grpc_web_hacker_news.Item.prototype.setId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.grpc_web_hacker_news.Item.prototype.clearId = function() {
  this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.grpc_web_hacker_news.Item.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 score = 2;
 * @return {number}
 */
proto.grpc_web_hacker_news.Item.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.grpc_web_hacker_news.Item.prototype.setScore = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string title = 3;
 * @return {string}
 */
proto.grpc_web_hacker_news.Item.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.grpc_web_hacker_news.Item.prototype.setTitle = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string by = 4;
 * @return {string}
 */
proto.grpc_web_hacker_news.Item.prototype.getBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.grpc_web_hacker_news.Item.prototype.setBy = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional int32 time = 5;
 * @return {number}
 */
proto.grpc_web_hacker_news.Item.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.grpc_web_hacker_news.Item.prototype.setTime = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string url = 6;
 * @return {string}
 */
proto.grpc_web_hacker_news.Item.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.grpc_web_hacker_news.Item.prototype.setUrl = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional ItemType type = 7;
 * @return {!proto.grpc_web_hacker_news.ItemType}
 */
proto.grpc_web_hacker_news.Item.prototype.getType = function() {
  return /** @type {!proto.grpc_web_hacker_news.ItemType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {!proto.grpc_web_hacker_news.ItemType} value */
proto.grpc_web_hacker_news.Item.prototype.setType = function(value) {
  jspb.Message.setField(this, 7, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_web_hacker_news.ListStoriesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_web_hacker_news.ListStoriesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_web_hacker_news.ListStoriesResponse.displayName = 'proto.grpc_web_hacker_news.ListStoriesResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_web_hacker_news.ListStoriesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_web_hacker_news.ListStoriesResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    story: (f = msg.getStory()) && proto.grpc_web_hacker_news.Item.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_web_hacker_news.ListStoriesResponse}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_web_hacker_news.ListStoriesResponse;
  return proto.grpc_web_hacker_news.ListStoriesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_web_hacker_news.ListStoriesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_web_hacker_news.ListStoriesResponse}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.grpc_web_hacker_news.Item;
      reader.readMessage(value,proto.grpc_web_hacker_news.Item.deserializeBinaryFromReader);
      msg.setStory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_web_hacker_news.ListStoriesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_web_hacker_news.ListStoriesResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_web_hacker_news.ListStoriesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStory();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.grpc_web_hacker_news.Item.serializeBinaryToWriter
    );
  }
};


/**
 * optional Item story = 1;
 * @return {?proto.grpc_web_hacker_news.Item}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.getStory = function() {
  return /** @type{?proto.grpc_web_hacker_news.Item} */ (
    jspb.Message.getWrapperField(this, proto.grpc_web_hacker_news.Item, 1));
};


/** @param {?proto.grpc_web_hacker_news.Item|undefined} value */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.setStory = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.grpc_web_hacker_news.ListStoriesResponse.prototype.clearStory = function() {
  this.setStory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.hasStory = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_web_hacker_news.ListStoriesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_web_hacker_news.ListStoriesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_web_hacker_news.ListStoriesRequest.displayName = 'proto.grpc_web_hacker_news.ListStoriesRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_web_hacker_news.ListStoriesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_web_hacker_news.ListStoriesRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_web_hacker_news.ListStoriesRequest}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_web_hacker_news.ListStoriesRequest;
  return proto.grpc_web_hacker_news.ListStoriesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_web_hacker_news.ListStoriesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_web_hacker_news.ListStoriesRequest}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_web_hacker_news.ListStoriesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_web_hacker_news.ListStoriesRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_web_hacker_news.ListStoriesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_web_hacker_news.GetStoryRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_web_hacker_news.GetStoryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_web_hacker_news.GetStoryRequest.displayName = 'proto.grpc_web_hacker_news.GetStoryRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_web_hacker_news.GetStoryRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_web_hacker_news.GetStoryRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_web_hacker_news.GetStoryRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_web_hacker_news.GetStoryRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto.grpc_web_hacker_news.ItemId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_web_hacker_news.GetStoryRequest}
 */
proto.grpc_web_hacker_news.GetStoryRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_web_hacker_news.GetStoryRequest;
  return proto.grpc_web_hacker_news.GetStoryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_web_hacker_news.GetStoryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_web_hacker_news.GetStoryRequest}
 */
proto.grpc_web_hacker_news.GetStoryRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.grpc_web_hacker_news.ItemId;
      reader.readMessage(value,proto.grpc_web_hacker_news.ItemId.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.GetStoryRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_web_hacker_news.GetStoryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_web_hacker_news.GetStoryRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_web_hacker_news.GetStoryRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.grpc_web_hacker_news.ItemId.serializeBinaryToWriter
    );
  }
};


/**
 * optional ItemId id = 1;
 * @return {?proto.grpc_web_hacker_news.ItemId}
 */
proto.grpc_web_hacker_news.GetStoryRequest.prototype.getId = function() {
  return /** @type{?proto.grpc_web_hacker_news.ItemId} */ (
    jspb.Message.getWrapperField(this, proto.grpc_web_hacker_news.ItemId, 1));
};


/** @param {?proto.grpc_web_hacker_news.ItemId|undefined} value */
proto.grpc_web_hacker_news.GetStoryRequest.prototype.setId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.grpc_web_hacker_news.GetStoryRequest.prototype.clearId = function() {
  this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.grpc_web_hacker_news.GetStoryRequest.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_web_hacker_news.GetStoryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_web_hacker_news.GetStoryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_web_hacker_news.GetStoryResponse.displayName = 'proto.grpc_web_hacker_news.GetStoryResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_web_hacker_news.GetStoryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_web_hacker_news.GetStoryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_web_hacker_news.GetStoryResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_web_hacker_news.GetStoryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    story: (f = msg.getStory()) && proto.grpc_web_hacker_news.Item.toObject(includeInstance, f),
    html: msg.getHtml_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_web_hacker_news.GetStoryResponse}
 */
proto.grpc_web_hacker_news.GetStoryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_web_hacker_news.GetStoryResponse;
  return proto.grpc_web_hacker_news.GetStoryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_web_hacker_news.GetStoryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_web_hacker_news.GetStoryResponse}
 */
proto.grpc_web_hacker_news.GetStoryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.grpc_web_hacker_news.Item;
      reader.readMessage(value,proto.grpc_web_hacker_news.Item.deserializeBinaryFromReader);
      msg.setStory(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setHtml(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.GetStoryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_web_hacker_news.GetStoryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_web_hacker_news.GetStoryResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_web_hacker_news.GetStoryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStory();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.grpc_web_hacker_news.Item.serializeBinaryToWriter
    );
  }
  f = message.getHtml_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional Item story = 1;
 * @return {?proto.grpc_web_hacker_news.Item}
 */
proto.grpc_web_hacker_news.GetStoryResponse.prototype.getStory = function() {
  return /** @type{?proto.grpc_web_hacker_news.Item} */ (
    jspb.Message.getWrapperField(this, proto.grpc_web_hacker_news.Item, 1));
};


/** @param {?proto.grpc_web_hacker_news.Item|undefined} value */
proto.grpc_web_hacker_news.GetStoryResponse.prototype.setStory = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.grpc_web_hacker_news.GetStoryResponse.prototype.clearStory = function() {
  this.setStory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.grpc_web_hacker_news.GetStoryResponse.prototype.hasStory = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes html = 2;
 * @return {!(string|Uint8Array)}
 */
proto.grpc_web_hacker_news.GetStoryResponse.prototype.getHtml = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes html = 2;
 * This is a type-conversion wrapper around `getHtml()`
 * @return {string}
 */
proto.grpc_web_hacker_news.GetStoryResponse.prototype.getHtml_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getHtml()));
};


/**
 * optional bytes html = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getHtml()`
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.GetStoryResponse.prototype.getHtml_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getHtml()));
};


/** @param {!(string|Uint8Array)} value */
proto.grpc_web_hacker_news.GetStoryResponse.prototype.setHtml = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.grpc_web_hacker_news.ItemType = {
  UNKNOWN: 0,
  JOB: 1,
  STORY: 2,
  COMMENT: 3,
  POLL: 4,
  POLLOPT: 5
};

goog.object.extend(exports, proto.grpc_web_hacker_news);
