/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.grpc_web_hacker_news.Item', null, global);
goog.exportSymbol('proto.grpc_web_hacker_news.ListStoriesRequest', null, global);
goog.exportSymbol('proto.grpc_web_hacker_news.ListStoriesResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_web_hacker_news.Item = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_web_hacker_news.Item, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_web_hacker_news.Item.displayName = 'proto.grpc_web_hacker_news.Item';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_web_hacker_news.Item.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_web_hacker_news.Item.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_web_hacker_news.Item} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_web_hacker_news.Item.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_web_hacker_news.Item}
 */
proto.grpc_web_hacker_news.Item.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_web_hacker_news.Item;
  return proto.grpc_web_hacker_news.Item.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_web_hacker_news.Item} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_web_hacker_news.Item}
 */
proto.grpc_web_hacker_news.Item.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.Item.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_web_hacker_news.Item.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_web_hacker_news.Item} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_web_hacker_news.Item.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.grpc_web_hacker_news.Item.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.grpc_web_hacker_news.Item.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_web_hacker_news.ListStoriesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.grpc_web_hacker_news.ListStoriesResponse.repeatedFields_, null);
};
goog.inherits(proto.grpc_web_hacker_news.ListStoriesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_web_hacker_news.ListStoriesResponse.displayName = 'proto.grpc_web_hacker_news.ListStoriesResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.grpc_web_hacker_news.ListStoriesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_web_hacker_news.ListStoriesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_web_hacker_news.ListStoriesResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    storiesList: jspb.Message.toObjectList(msg.getStoriesList(),
    proto.grpc_web_hacker_news.Item.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_web_hacker_news.ListStoriesResponse}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_web_hacker_news.ListStoriesResponse;
  return proto.grpc_web_hacker_news.ListStoriesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_web_hacker_news.ListStoriesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_web_hacker_news.ListStoriesResponse}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.grpc_web_hacker_news.Item;
      reader.readMessage(value,proto.grpc_web_hacker_news.Item.deserializeBinaryFromReader);
      msg.addStories(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_web_hacker_news.ListStoriesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_web_hacker_news.ListStoriesResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_web_hacker_news.ListStoriesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStoriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.grpc_web_hacker_news.Item.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Item stories = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.grpc_web_hacker_news.Item>}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.getStoriesList = function() {
  return /** @type{!Array.<!proto.grpc_web_hacker_news.Item>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.grpc_web_hacker_news.Item, 1));
};


/** @param {!Array.<!proto.grpc_web_hacker_news.Item>} value */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.setStoriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.grpc_web_hacker_news.Item=} opt_value
 * @param {number=} opt_index
 * @return {!proto.grpc_web_hacker_news.Item}
 */
proto.grpc_web_hacker_news.ListStoriesResponse.prototype.addStories = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.grpc_web_hacker_news.Item, opt_index);
};


proto.grpc_web_hacker_news.ListStoriesResponse.prototype.clearStoriesList = function() {
  this.setStoriesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_web_hacker_news.ListStoriesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_web_hacker_news.ListStoriesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_web_hacker_news.ListStoriesRequest.displayName = 'proto.grpc_web_hacker_news.ListStoriesRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_web_hacker_news.ListStoriesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_web_hacker_news.ListStoriesRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_web_hacker_news.ListStoriesRequest}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_web_hacker_news.ListStoriesRequest;
  return proto.grpc_web_hacker_news.ListStoriesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_web_hacker_news.ListStoriesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_web_hacker_news.ListStoriesRequest}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_web_hacker_news.ListStoriesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_web_hacker_news.ListStoriesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_web_hacker_news.ListStoriesRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_web_hacker_news.ListStoriesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.grpc_web_hacker_news);
