// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hackernews.proto

/*
Package grpc_web_hacker_news is a generated protocol buffer package.

It is generated from these files:
	proto/hackernews.proto

It has these top-level messages:
	ItemId
	Item
	ListStoriesResponse
	ListStoriesRequest
	GetStoryRequest
	GetStoryResponse
*/
package grpc_web_hacker_news

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ItemType int32

const (
	ItemType_UNKNOWN ItemType = 0
	ItemType_JOB     ItemType = 1
	ItemType_STORY   ItemType = 2
	ItemType_COMMENT ItemType = 3
	ItemType_POLL    ItemType = 4
	ItemType_POLLOPT ItemType = 5
)

var ItemType_name = map[int32]string{
	0: "UNKNOWN",
	1: "JOB",
	2: "STORY",
	3: "COMMENT",
	4: "POLL",
	5: "POLLOPT",
}
var ItemType_value = map[string]int32{
	"UNKNOWN": 0,
	"JOB":     1,
	"STORY":   2,
	"COMMENT": 3,
	"POLL":    4,
	"POLLOPT": 5,
}

func (x ItemType) String() string {
	return proto.EnumName(ItemType_name, int32(x))
}
func (ItemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ItemId struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ItemId) Reset()                    { *m = ItemId{} }
func (m *ItemId) String() string            { return proto.CompactTextString(m) }
func (*ItemId) ProtoMessage()               {}
func (*ItemId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ItemId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Item struct {
	Id    *ItemId  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Score int32    `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	Title string   `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	By    string   `protobuf:"bytes,4,opt,name=by" json:"by,omitempty"`
	Time  int32    `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
	Url   string   `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
	Type  ItemType `protobuf:"varint,7,opt,name=type,enum=grpc_web_hacker_news.ItemType" json:"type,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Item) GetId() *ItemId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Item) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetBy() string {
	if m != nil {
		return m.By
	}
	return ""
}

func (m *Item) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Item) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Item) GetType() ItemType {
	if m != nil {
		return m.Type
	}
	return ItemType_UNKNOWN
}

type ListStoriesResponse struct {
	Story *Item `protobuf:"bytes,1,opt,name=story" json:"story,omitempty"`
}

func (m *ListStoriesResponse) Reset()                    { *m = ListStoriesResponse{} }
func (m *ListStoriesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListStoriesResponse) ProtoMessage()               {}
func (*ListStoriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListStoriesResponse) GetStory() *Item {
	if m != nil {
		return m.Story
	}
	return nil
}

type ListStoriesRequest struct {
}

func (m *ListStoriesRequest) Reset()                    { *m = ListStoriesRequest{} }
func (m *ListStoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListStoriesRequest) ProtoMessage()               {}
func (*ListStoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetStoryRequest struct {
	Id *ItemId `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetStoryRequest) Reset()                    { *m = GetStoryRequest{} }
func (m *GetStoryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStoryRequest) ProtoMessage()               {}
func (*GetStoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetStoryRequest) GetId() *ItemId {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetStoryResponse struct {
	Story *Item  `protobuf:"bytes,1,opt,name=story" json:"story,omitempty"`
	Html  []byte `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
}

func (m *GetStoryResponse) Reset()                    { *m = GetStoryResponse{} }
func (m *GetStoryResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStoryResponse) ProtoMessage()               {}
func (*GetStoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetStoryResponse) GetStory() *Item {
	if m != nil {
		return m.Story
	}
	return nil
}

func (m *GetStoryResponse) GetHtml() []byte {
	if m != nil {
		return m.Html
	}
	return nil
}

func init() {
	proto.RegisterType((*ItemId)(nil), "grpc_web_hacker_news.ItemId")
	proto.RegisterType((*Item)(nil), "grpc_web_hacker_news.Item")
	proto.RegisterType((*ListStoriesResponse)(nil), "grpc_web_hacker_news.ListStoriesResponse")
	proto.RegisterType((*ListStoriesRequest)(nil), "grpc_web_hacker_news.ListStoriesRequest")
	proto.RegisterType((*GetStoryRequest)(nil), "grpc_web_hacker_news.GetStoryRequest")
	proto.RegisterType((*GetStoryResponse)(nil), "grpc_web_hacker_news.GetStoryResponse")
	proto.RegisterEnum("grpc_web_hacker_news.ItemType", ItemType_name, ItemType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HackerNewsService service

type HackerNewsServiceClient interface {
	ListStories(ctx context.Context, in *ListStoriesRequest, opts ...grpc.CallOption) (HackerNewsService_ListStoriesClient, error)
	GetStory(ctx context.Context, in *GetStoryRequest, opts ...grpc.CallOption) (*GetStoryResponse, error)
}

type hackerNewsServiceClient struct {
	cc *grpc.ClientConn
}

func NewHackerNewsServiceClient(cc *grpc.ClientConn) HackerNewsServiceClient {
	return &hackerNewsServiceClient{cc}
}

func (c *hackerNewsServiceClient) ListStories(ctx context.Context, in *ListStoriesRequest, opts ...grpc.CallOption) (HackerNewsService_ListStoriesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_HackerNewsService_serviceDesc.Streams[0], c.cc, "/grpc_web_hacker_news.HackerNewsService/ListStories", opts...)
	if err != nil {
		return nil, err
	}
	x := &hackerNewsServiceListStoriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HackerNewsService_ListStoriesClient interface {
	Recv() (*ListStoriesResponse, error)
	grpc.ClientStream
}

type hackerNewsServiceListStoriesClient struct {
	grpc.ClientStream
}

func (x *hackerNewsServiceListStoriesClient) Recv() (*ListStoriesResponse, error) {
	m := new(ListStoriesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hackerNewsServiceClient) GetStory(ctx context.Context, in *GetStoryRequest, opts ...grpc.CallOption) (*GetStoryResponse, error) {
	out := new(GetStoryResponse)
	err := grpc.Invoke(ctx, "/grpc_web_hacker_news.HackerNewsService/GetStory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HackerNewsService service

type HackerNewsServiceServer interface {
	ListStories(*ListStoriesRequest, HackerNewsService_ListStoriesServer) error
	GetStory(context.Context, *GetStoryRequest) (*GetStoryResponse, error)
}

func RegisterHackerNewsServiceServer(s *grpc.Server, srv HackerNewsServiceServer) {
	s.RegisterService(&_HackerNewsService_serviceDesc, srv)
}

func _HackerNewsService_ListStories_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListStoriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HackerNewsServiceServer).ListStories(m, &hackerNewsServiceListStoriesServer{stream})
}

type HackerNewsService_ListStoriesServer interface {
	Send(*ListStoriesResponse) error
	grpc.ServerStream
}

type hackerNewsServiceListStoriesServer struct {
	grpc.ServerStream
}

func (x *hackerNewsServiceListStoriesServer) Send(m *ListStoriesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HackerNewsService_GetStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HackerNewsServiceServer).GetStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_web_hacker_news.HackerNewsService/GetStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HackerNewsServiceServer).GetStory(ctx, req.(*GetStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HackerNewsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_web_hacker_news.HackerNewsService",
	HandlerType: (*HackerNewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStory",
			Handler:    _HackerNewsService_GetStory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListStories",
			Handler:       _HackerNewsService_ListStories_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/hackernews.proto",
}

func init() { proto.RegisterFile("proto/hackernews.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x6f, 0x8b, 0xd3, 0x40,
	0x10, 0xc6, 0xdd, 0xfc, 0x69, 0x7b, 0x53, 0x39, 0xd7, 0xb1, 0xc8, 0x52, 0x44, 0x4a, 0x40, 0x89,
	0x22, 0xf5, 0x88, 0x1f, 0x40, 0x50, 0xe4, 0x3c, 0xed, 0x25, 0x47, 0x1a, 0xd1, 0x7b, 0x55, 0x4c,
	0x32, 0x78, 0xc1, 0xf6, 0x12, 0x77, 0xf7, 0x2c, 0xf9, 0x8a, 0xbe, 0xf6, 0x03, 0xc9, 0x6e, 0xae,
	0xfe, 0x6d, 0x51, 0xef, 0xdd, 0xcc, 0x33, 0xcf, 0x3c, 0x99, 0xfc, 0x42, 0xe0, 0x76, 0x23, 0x6b,
	0x5d, 0x3f, 0x3e, 0x7b, 0x5f, 0x7c, 0x24, 0x79, 0x4e, 0x6b, 0x35, 0xb5, 0x02, 0x8e, 0x3e, 0xc8,
	0xa6, 0x58, 0xac, 0x29, 0x5f, 0x74, 0xa3, 0x85, 0x99, 0x05, 0x02, 0x7a, 0x47, 0x9a, 0x56, 0x47,
	0x25, 0xee, 0x83, 0x53, 0x95, 0x82, 0x4d, 0x58, 0xe8, 0xa7, 0x4e, 0x55, 0x06, 0x5f, 0x18, 0x78,
	0x66, 0x84, 0x8f, 0xbe, 0x0f, 0x86, 0xd1, 0x9d, 0xe9, 0xb6, 0x94, 0x69, 0x17, 0x61, 0xd6, 0x70,
	0x04, 0xbe, 0x2a, 0x6a, 0x49, 0xc2, 0xb1, 0x49, 0x5d, 0x63, 0x54, 0x5d, 0xe9, 0x25, 0x09, 0x77,
	0xc2, 0xc2, 0xbd, 0xb4, 0x6b, 0xcc, 0x23, 0xf3, 0x56, 0x78, 0x56, 0x72, 0xf2, 0x16, 0x11, 0x3c,
	0x5d, 0xad, 0x48, 0xf8, 0x76, 0xd5, 0xd6, 0xc8, 0xc1, 0xbd, 0x90, 0x4b, 0xd1, 0xb3, 0x26, 0x53,
	0x62, 0x04, 0x9e, 0x6e, 0x1b, 0x12, 0xfd, 0x09, 0x0b, 0xf7, 0xa3, 0xbb, 0xbb, 0x2f, 0xca, 0xda,
	0x86, 0x52, 0xeb, 0x0d, 0x0e, 0xe1, 0xd6, 0xac, 0x52, 0x7a, 0xae, 0x6b, 0x59, 0x91, 0x4a, 0x49,
	0x35, 0xf5, 0xb9, 0x22, 0x3c, 0x00, 0x5f, 0xe9, 0x5a, 0xb6, 0x97, 0x6f, 0x37, 0xde, 0x9d, 0x95,
	0x76, 0xc6, 0x60, 0x04, 0xf8, 0x4b, 0xd0, 0xa7, 0x0b, 0x52, 0x3a, 0x78, 0x0a, 0x37, 0x0e, 0xc9,
	0x8a, 0xed, 0xa5, 0xf4, 0x7f, 0xd4, 0x82, 0x77, 0xc0, 0x7f, 0x04, 0x5c, 0xf5, 0x38, 0xc3, 0xef,
	0x4c, 0xaf, 0x96, 0x16, 0xfd, 0xf5, 0xd4, 0xd6, 0x0f, 0x13, 0x18, 0x6c, 0x58, 0xe0, 0x10, 0xfa,
	0x6f, 0xe2, 0xd7, 0x71, 0xf2, 0x36, 0xe6, 0xd7, 0xb0, 0x0f, 0xee, 0xab, 0xe4, 0x19, 0x67, 0xb8,
	0x07, 0xfe, 0x3c, 0x4b, 0xd2, 0x53, 0xee, 0x18, 0xc3, 0xf3, 0xe4, 0xf8, 0xf8, 0x45, 0x9c, 0x71,
	0x17, 0x07, 0xe0, 0x9d, 0x24, 0xb3, 0x19, 0xf7, 0x8c, 0x6c, 0xaa, 0xe4, 0x24, 0xe3, 0x7e, 0xf4,
	0x95, 0xc1, 0xcd, 0x97, 0xf6, 0x80, 0x98, 0xd6, 0x6a, 0x4e, 0xf2, 0x73, 0x55, 0x10, 0x96, 0x30,
	0xfc, 0x89, 0x0b, 0x86, 0xdb, 0x8f, 0xfd, 0x13, 0xdd, 0xf8, 0xc1, 0x3f, 0x38, 0x3b, 0x20, 0x07,
	0x0c, 0x4f, 0x61, 0xb0, 0xc1, 0x84, 0xf7, 0xb6, 0x2f, 0xfe, 0xf6, 0x1d, 0xc6, 0xf7, 0xff, 0x66,
	0xeb, 0xc2, 0xf3, 0x9e, 0xfd, 0x4b, 0x9e, 0x7c, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x93, 0x8c,
	0x48, 0x3f, 0x03, 0x00, 0x00,
}
