// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hackernews.proto

/*
Package grpc_web_hacker_news is a generated protocol buffer package.

It is generated from these files:
	proto/hackernews.proto

It has these top-level messages:
	Item
	ListStoriesResponse
	ListStoriesRequest
*/
package grpc_web_hacker_news

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListStoriesResponse struct {
	Stories []*Item `protobuf:"bytes,1,rep,name=stories" json:"stories,omitempty"`
}

func (m *ListStoriesResponse) Reset()                    { *m = ListStoriesResponse{} }
func (m *ListStoriesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListStoriesResponse) ProtoMessage()               {}
func (*ListStoriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListStoriesResponse) GetStories() []*Item {
	if m != nil {
		return m.Stories
	}
	return nil
}

type ListStoriesRequest struct {
}

func (m *ListStoriesRequest) Reset()                    { *m = ListStoriesRequest{} }
func (m *ListStoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListStoriesRequest) ProtoMessage()               {}
func (*ListStoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Item)(nil), "grpc_web_hacker_news.Item")
	proto.RegisterType((*ListStoriesResponse)(nil), "grpc_web_hacker_news.ListStoriesResponse")
	proto.RegisterType((*ListStoriesRequest)(nil), "grpc_web_hacker_news.ListStoriesRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HackerNewsService service

type HackerNewsServiceClient interface {
	ListStories(ctx context.Context, in *ListStoriesRequest, opts ...grpc.CallOption) (*ListStoriesResponse, error)
}

type hackerNewsServiceClient struct {
	cc *grpc.ClientConn
}

func NewHackerNewsServiceClient(cc *grpc.ClientConn) HackerNewsServiceClient {
	return &hackerNewsServiceClient{cc}
}

func (c *hackerNewsServiceClient) ListStories(ctx context.Context, in *ListStoriesRequest, opts ...grpc.CallOption) (*ListStoriesResponse, error) {
	out := new(ListStoriesResponse)
	err := grpc.Invoke(ctx, "/grpc_web_hacker_news.HackerNewsService/ListStories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HackerNewsService service

type HackerNewsServiceServer interface {
	ListStories(context.Context, *ListStoriesRequest) (*ListStoriesResponse, error)
}

func RegisterHackerNewsServiceServer(s *grpc.Server, srv HackerNewsServiceServer) {
	s.RegisterService(&_HackerNewsService_serviceDesc, srv)
}

func _HackerNewsService_ListStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HackerNewsServiceServer).ListStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_web_hacker_news.HackerNewsService/ListStories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HackerNewsServiceServer).ListStories(ctx, req.(*ListStoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HackerNewsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_web_hacker_news.HackerNewsService",
	HandlerType: (*HackerNewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStories",
			Handler:    _HackerNewsService_ListStories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hackernews.proto",
}

func init() { proto.RegisterFile("proto/hackernews.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x48, 0x4c, 0xce, 0x4e, 0x2d, 0xca, 0x4b, 0x2d, 0x2f, 0xd6, 0x03, 0x0b, 0x08,
	0x89, 0xa4, 0x17, 0x15, 0x24, 0xc7, 0x97, 0xa7, 0x26, 0xc5, 0x43, 0xa4, 0xe2, 0x41, 0x72, 0x4a,
	0x62, 0x5c, 0x2c, 0x9e, 0x25, 0xa9, 0xb9, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x4a, 0xde, 0x5c, 0xc2, 0x3e, 0x99, 0xc5, 0x25, 0xc1,
	0x25, 0xf9, 0x45, 0x99, 0xa9, 0xc5, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x26,
	0x5c, 0xec, 0xc5, 0x10, 0x21, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x29, 0x3d, 0x6c, 0xc6,
	0xea, 0x81, 0xcc, 0x0c, 0x82, 0x29, 0x55, 0x12, 0xe1, 0x12, 0x42, 0x31, 0xac, 0xb0, 0x34, 0xb5,
	0xb8, 0xc4, 0xa8, 0x9c, 0x4b, 0xd0, 0x03, 0xac, 0xc5, 0x2f, 0xb5, 0xbc, 0x38, 0x38, 0xb5, 0xa8,
	0x2c, 0x33, 0x39, 0x55, 0x28, 0x89, 0x8b, 0x1b, 0x49, 0xa9, 0x90, 0x06, 0x76, 0xe3, 0x31, 0x4d,
	0x93, 0xd2, 0x24, 0x42, 0x25, 0xc4, 0x13, 0x49, 0x6c, 0xe0, 0x00, 0x31, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x7a, 0x2e, 0x50, 0x56, 0x2a, 0x01, 0x00, 0x00,
}
